### PR TITLE
Update plot_price_NAs function

### PR DESCRIPTION
**Pull request by tallosfarkas**
Updated the plot_price_NAs function with enhanced visualization and better compliance with standards.

### CODE REVIEW

**Review by Jaekoeb — CHANGES_REQUESTED** [review]
Hi Farkas,
thanks for the updated version. I am happy to see that you are already working on the engine.

Unfortunately I can't run the function. This is because you have not added the pipe operator `%>%` to the imports from the `dplyr` package.

Alternatively there is a native pipe operator in base R `|>` which does the same thing. In principle both pipe operators are the same. The base version is theoretically a bit faster, but has less functionalities but I have nerver run into a case where `|>` didn't work and `%>%` did. (There is also an option in Rstudio to change the shortcut "Control + Shift + M" to the native one.

Please change in any way you see fit, then we can merge.

Thank you!

**Comment by tallosfarkas** [comment]
Hi @Jaekoeb, I've updated the plot_price_NAs function to use the base R pipe operator \`|>\`. Let me know if there's anything else needed for the merge.

**Review by Jaekoeb — CHANGES_REQUESTED** [review]
Hi Farkas,
thanks for the change. However still one `%>%` pipe operator remains in the code. Also when I changed it myself I saw that `element_line()` is not imported. Finally I fixed these changes and got a plot but I think that it does not quite work out. See an example attached.

Please fix these issues, then we can merge. Thank you!

plot_price_Nas

**Comment by tallosfarkas** [comment]
Hey Jakob!

Sorry for not being precise, hopefully I solved everything.
Regarding the plot, I could recreate the situation and with resizing or opening in new window it works fine for me, unfortunately it is not dynamic in that sense, for a lot of assets it needs space. 

image
image

**Comment by tallosfarkas** [comment]
Updated the plot_price_NAs function to optimize performance for 10+ years of daily data. Let me know if there’s anything else needed for the merge.

**Comment by tallosfarkas** [comment]
Updated the plot_price_NAs function to optimize performance for 10+ years of daily data. Let me know if there’s anything else needed for the merge.

**Comment by tallosfarkas** [comment]
The updates to the plot_price_NAs function are complete, and the function now handles 10 years of daily data efficiently. Let me know if further adjustments are needed!

image

**Review by Jaekoeb — DISMISSED** [review]
Hi Farkas, I just ran the function and it works out perfectly. Thank you for the work it looks much nicer now. Please proceed to merge the branch.

**Review by Jaekoeb — APPROVED** [review]
Looks good thanks!

**Pull request merged**
